### ISSUE TITLE
Create a Queue System that supports basic features and webhooks

### ISSUE THREAD

**Issue by SirPolaris** [Citizen-Group/Que#1]
**Part of:** Queue Development

**Prio:** Medium - 3

The City of Ottawa requires a custom "physical queue" (lineup) system to replace the paper driven system at their service centers. Having an basic digital queue frees up resources and allows for other tools to provide systems and features. The end objective will be to have a queue system that allows for basic CRUD operations, as well as a few custom features to provide display and statistical information.

**Expected results:**
- [ ] Build a basic software queue that persists to a mongo database #11
- [ ] The queue will produce statistics and store them #5 
- [ ] Allow users to be "called up" without affecting their place in the queue
   - [ ] Allow for a mobile application to page them #10 
- [ ] Use a standardized ID system to track users #2
